# Generated by Django 3.1.7 on 2021-03-29 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210328_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['date_joined']},
        ),
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='photos/default-user-avatar.png', upload_to='photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='account',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Mobile phone'),
        ),
        migrations.AddField(
            model_name='account',
            name='sector',
            field=models.CharField(default='Diğer', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='title',
            field=models.CharField(default='Title', max_length=30),
        ),
    ]
